# Generated by Django 5.2.17 on 2026-09-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('provider', models.CharField(db_index=True, max_length=255)),
                ('opportunity_type', models.CharField(choices=[('Scheme', 'Government Scheme'), ('Course', 'Free/Paid Course'), ('Internship', 'Internship'), ('Job', 'Job Opening'), ('Hackathon', 'Hackathon/Contest'), ('Certification', 'Certification Program')], db_index=True, max_length=30)),
                ('is_free', models.BooleanField(db_index=True, default=True)),
                ('stipend_or_cost', models.CharField(blank=True, default='Free', max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=20)),
                ('location', models.CharField(db_index=True, default='Pan-India', max_length=255)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(db_index=True)),
                ('matching_skills', models.JSONField(default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.DeleteModel(
            name='CareerPath',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interview_questions',
            field=models.JSONField(default=list, help_text='Tailored mock interview questions'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_improvements',
            field=models.JSONField(default=list, help_text='Actionable formatting/content suggestions'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_skills',
            field=models.JSONField(default=list, help_text='List of extracted candidate skills'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skill_gaps',
            field=models.JSONField(default=list, help_text='List of missing skills for target role'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='target_role',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type', 'is_free', 'is_active'], name='career_app__opportu_e5a2d5_idx'),
        ),
        migrations.AddField(
            model_name='opportunityskill',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='career_app.opportunity'),
        ),
        migrations.AddField(
            model_name='profilematch',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_matches', to='career_app.opportunity'),
        ),
        migrations.AddField(
            model_name='profilematch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='career_app.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityskill',
            unique_together={('opportunity', 'skill_name')},
        ),
        migrations.AlterUniqueTogether(
            name='profilematch',
            unique_together={('profile', 'opportunity')},
        ),
    ]
