# Generated by Django 5.2.17 on 2026-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "career_app",
            "0004_careerrole_courserecommendation_interviewquestion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="mode",
            field=models.CharField(default="Online", max_length=50),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_type",
            field=models.CharField(
                db_index=True,
                help_text="e.g., Job, Internship, Scheme, Fellowship",
                max_length=100,
            ),
        ),
    ]
