# Generated by Django 5.2.17 on 2026-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_app", "0007_resumeanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
