# Generated by Django 5.2.17 on 2026-09-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_app", "0008_resumeanalysis_resume_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="interview_feedbacks",
            field=models.JSONField(default=dict),
        ),
    ]
