# Generated by Django 5.2.17 on 2026-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0010_profilematch_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='interview_feedbacks',
            field=models.JSONField(default=dict, help_text='Saved mock interview answers and feedbacks'),
        ),
        migrations.AlterField(
            model_name='profilematch',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
    ]
